using System;
using System.Speech.Synthesis;

namespace TextToVoice
{
    internal class Program
    {
        static void Main(string[] args)
        {
            // Initialize a new instance of the SpeechSynthesizer class
            SpeechSynthesizer synth = new SpeechSynthesizer();

            // Configure the audio output
            synth.SetOutputToDefaultAudioDevice();

            // Choose a voice from the installed voices on your system
            synth.SelectVoiceByHints(VoiceGender.Female, VoiceAge.Adult);

            // Speak the text
            synth.Speak("Hello, I'm a text-to-speech voice generated by C#");

            Console.WriteLine("Press any key to exit...");
            Console.ReadKey();
        }
    }
}